### ISSUE TITLE
CANCELLED: Failed to stream message

### ISSUE THREAD

**Issue by godfatherzzx** [akka/akka-grpc#756] opened 2019-12-10 04:40 UTC
I got some errors like this:
**CANCELLED: Failed to stream message** 
And
**akka.http.scaladsl.model.http2.PeerClosedStreamException: Stream with ID [3] was closed by peer with code CANCEL(0x08)**

the proto file looks like this:
message AddEntity {
  string taskId=1;
  string itemId=2;
  string content=3;
  string userId=4;
  string extension=5;
  int32 kind=6;
}

message Done {
}

service ClusterService {
  rpc addEntity (AddEntity) returns (Done);
}

the client code and the application.conf:
  private val clientSettings = GrpcClientSettings.fromConfig(ClusterService.name)
  private val client = ClusterServiceClient(clientSettings)

akka.grpc.client {
  "com.xxx.xxx.service.api.ClusterService" {
	service-discovery {
	  mechanism = "config"
	  service-name = "from-config"
	  protocol = "tcp"
	  port-name = "http"
	}
	port = 9201
	use-tls = false
  }
}

akka.discovery.config.services = {
   from-config {
	 endpoints = [
	   {
		 host = "xx.xx.xx.xx"
		 port = 9200
	   },
	   {
		 host = "xx.xx.xx.xx"
		 port = 9200
	   },
	   {
		  host = "xx.xx.xx.xx"
		 port = 9200
	   },
	   {
		  host = "xx.xx.xx.xx"
		 port = 9200
	   }
	 ]
   }
 }

the server code like this:
val clusterServiceHandler = ClusterServiceHandler.partial(new ClusterServiceImpl(system))
    val serviceHandlers: HttpRequest => Future[HttpResponse] = ServiceHandler.concatOrNotFound(clusterServiceHandler)
    val serverBinding = Http2().bindAndHandleAsync(
      serviceHandlers,
      interface = host,
      port = config.getInt("server.port"),
      connectionContext = HttpConnectionContext(),
      parallelism = 256
    )
    serverBinding.onComplete {
      case Success(bound) =>
        logger.info(s"Cluster server classic online at http://${bound.localAddress.getHostString}:${bound.localAddress.getPort}/")
      case Failure(e) =>
        logger.error(s"Cluster server classic can not start! message :{}", e.getMessage())
        system.terminate()
    }
    Await.result(system.whenTerminated, Duration.Inf)

#357 
I tried modify the parallelism, but it did not work. Can someone help me ?

**Comment by raboof** [comment] 2019-12-10 09:27
Are you using Akka gRPC on both sides of this exchange? On which side do you see this log message?

**Comment by godfatherzzx** [comment] 2019-12-10 09:58
no, on the client side, the error message is:
**CANCELLED: Failed to stream message**
and on the server side the error message is:
**akka.http.scaladsl.model.http2.PeerClosedStreamException: Stream with ID [3] was closed by peer with code CANCEL(0x08)**

**Comment by raboof** [comment] 2019-12-10 10:04
So you are using Akka gRPC only on the server side? What are you using on the client side?

The error message on the server side suggests the client made the decision to cancel the stream. This could of course very well be caused by something that went wrong on the server side - but we should look at the client side for further diagnostics. I'd be happy to have a closer look if you can find a way for me to reproduce the problem.

**Comment by godfatherzzx** [comment] 2019-12-10 10:44
For some reason, the server needs to create many sharding regions according to the "taskId" in a short time. Maybe It needs time to create a new sharding region or recovery from the journal or snapshot, so the server side went wrong. Thank you for your help.

**Comment by raboof** [comment] 2019-12-10 11:04
I guess so - so your theory for now is that this is an application-level issue and not a problem in Akka gRPC?

I'll close the issue for now then, but feel free to re-open if you find additional information that suggests Akka gRPC is doing something wrong somewhere.

**Closed by raboof** 2019-12-10 11:04 UTC
