### ISSUE TITLE
Introduce scaladsl package in runtime lib

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-grpc#71] opened 2018-03-09 10:23 UTC
We have now a `javadsl` package but all Scala classes on still in `akka.http.grpc`. We should move them to `akka.http.grpc.scaladsl` or at least some of them.

**Comment by raboof** [comment] 2018-04-13 08:00
oops, #116 was a duplicate of this one

**Closed by raboof** 2018-04-13 08:00 UTC
