### ISSUE TITLE
Gradle build not working for scala project

### ISSUE THREAD

**Issue by Chr1stian** [akka/akka-grpc#1048] opened 2020-07-03 10:56 UTC
```
An exception occurred applying plugin request [id: 'com.lightbend.akka.grpc.gradle', version: '1.0.0-14-9cd5b41c']
> Failed to apply plugin [id 'com.lightbend.akka.grpc.gradle']
   > Could not find method protobuf() for arguments [akka.grpc.gradle.AkkaGrpcPlugin$_apply_closure1$_closure2@716c60f4] on root project 'project_name' of type org.gradle.api.Project.
```

Only thing I added was
```
plugins {
    id "com.lightbend.akka.grpc.gradle" version "1.0.0-14-9cd5b41c"
}
```

**Comment by raboof** [comment] 2020-07-03 14:59
Thanks for reporting!

This seems like a duplicate of #716, so I'll close this one and answer there.

**Closed by raboof** 2020-07-03 14:59 UTC
Labels: gradle
