### ISSUE TITLE
Client connection terminates unexpectedly on first call

### ISSUE THREAD

**Issue by ryanhanks** [akka/akka-grpc#1081] opened 2020-07-28 02:23 UTC
### Versions used 
akka-grpc 1.0.1, akka-grpc-quickstart project

### Expected Behavior

The request completes successfully.

### Actual Behavior

Akka-grpc server terminates stream unexpectedly on first call for new connection.

A full description with steps to reproduce can be found [here](https://github.com/ryanhanks/akka-dart-grpc-connection-bug)

The client being used is a dart client. It's fair to assume part (or all) of the issue resides in that codebase, so I will cross-post this issue to the dart-grpc project. However, it's worth noting that I wasn't able to reproduce this with the same client/test against a python backend.

I was able to reproduce this with both the java and scala quickstart projects. In both cases, the only modification made was to use an HTTP connection instead of HTTPS. I'm not sure if this reproduces with HTTPS connections.

### Relevant logs

I used the akka-grpc-quickstart project to reproduce. 

### Reproducible Test Case

Please see https://github.com/ryanhanks/akka-dart-grpc-connection-bug

**Comment by ryanhanks** [comment] 2020-07-28 02:34
Cross-post to grpc-dart: https://github.com/grpc/grpc-dart/issues/334

**Comment by raboof** [comment] 2020-08-12 08:51
Thank you for this excellent report with reproducer.

I have looked into this somewhat, and at first glance it indeed seems to be a problem on the Akka gRPC/Akka HTTP side.

For me it's not consistently the 'first call' that fails, it's just failing now and then inconsistently - I suspect a race condition.

Looking at the exchange in wireshark, for each request, the dart code sends 1 data frame with a protobuf object, and then 1 'empty' data frame signalling the end of the stream. That's fine.

It appears that after reading the protobuf object, Akka gRPC cancels the stream. That's not necessarily wrong (it's just a way to signal that Akka gRPC is no longer interested in any further data), but perhaps it would be nicer to avoid it.

However, after that a couple of problematic things appear to happen (more verification needed):
* Due to this cancellation, Akka HTTP resets the stream with code 'CANCEL', moving the whole stream (both the reading and the writing side) to Closed. That seems premature.
* It then also sends a GOAWAY frame for the whole connection (that seems wrong to me, it was just this one stream that got cancelled)
* And finally it sends the reply, even though the stream was already closed.

Those are things we should look into and fix.

Possibly we could work around these particular problems in Akka gRPC by not cancelling the request, but that seems to ignore the 'real' issues.

**Comment by jrudolph** [comment] 2020-09-03 12:11
> It then also sends a GOAWAY frame for the whole connection (that seems wrong to me, it was just this one stream that got cancelled)

This part is fixed with https://github.com/akka/akka-http/pull/3462

**Comment by raboof** [comment] 2020-09-22 13:29
I think this is fixed with the combination of akka/akka-http#3462 and #1111 . I'll do a 1.0.2 release soon, until that time you should be able to get the 1.0.1-33-10aad695 snapshot.

**Closed** 2020-09-22 13:29 UTC
Labels: bug
